name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest #최신 우분투 실행
    steps:
      - run: echo 'Hello, GiHub Actions!'
  pwd-ls: 
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Pring working directory
        run: pwd
      - name: List files
        run: ls -al
      
