name: Java CI with Gradle

on: 
  push: 
    branches: [ "sunghyun-develop" ]
  pull_request: 
    branches: [ "sunghyun-develop" ]
    
jobs:
  build:
    name: create properties
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: mkdir ./src/main/resources/properties
      
      - run: touch ./src/main/resources/properties/fileUpload.properties
      - run: echo "${{secrets.FILEUPLOAD}}" > ./src/main/resources/properties/fileUpload.properties
      
      - run: touch ./src/main/resources/properties/fileUpload.properties
      - run: echo "${{secrets.DATASOURCE}}" > ./src/main/resources/properties/datasource.properties
      
      - run: touch ./src/main/resources/properties/fileUpload.properties
      - run: echo "${{secrets.LOGGING}}" > ./src/main/resources/properties/logging.properties
      
      - run: touch ./src/main/resources/properties/fileUpload.properties
      - run: echo "${{secrets.MAIL}}" > ./src/main/resources/properties/mail.properties
      
      - run: touch ./src/main/resources/properties/oauth2.properties
      - run: echo "${{secrets.OAUTH2}}" > ./src/main/resources/properties/oauth2.properties
      - run: cat ./src/main/resources/properties/oauth2.properites
      
      - run: ls -lrt ./src/main/resources/properties

      - uses: actions/upload-artifact@v3
        with:
          name: properties
          path: ./src/main/resources/properties/*

